from django.db import models
from ..core.models import Cidade, MotoPerfil
from ..account.models import Perfil

class CidadeModelo(models.Model):
    cidade = models.ForeignKey(Cidade, on_delete=models.CASCADE)
    modelo = models.ForeignKey(MotoPerfil, on_delete=models.CASCADE)
    aplicado = models.IntegerField(null=True) 
    previsto = models.IntegerField(null=True) 
    ano = models.IntegerField(null=True) 
    aplicado_jan = models.IntegerField(null=True) 
    aplicado_fev = models.IntegerField(null=True) 
    aplicado_mar = models.IntegerField(null=True) 
    aplicado_abr = models.IntegerField(null=True) 
    aplicado_mai = models.IntegerField(null=True) 
    aplicado_jun = models.IntegerField(null=True) 
    aplicado_jul = models.IntegerField(null=True) 
    aplicado_ago = models.IntegerField(null=True) 
    aplicado_sete = models.IntegerField(null=True) 
    aplicado_out = models.IntegerField(null=True) 
    aplicado_nov = models.IntegerField(null=True) 
    aplicado_dez = models.IntegerField(null=True) 
    previsto_jan = models.IntegerField(null=True) 
    previsto_fev = models.IntegerField(null=True) 
    previsto_mar = models.IntegerField(null=True) 
    previsto_abr = models.IntegerField(null=True) 
    previsto_mai = models.IntegerField(null=True) 
    previsto_jun = models.IntegerField(null=True) 
    previsto_jul = models.IntegerField(null=True) 
    previsto_ago = models.IntegerField(null=True) 
    previsto_sete = models.IntegerField(null=True) 
    previsto_out = models.IntegerField(null=True) 
    previsto_nov = models.IntegerField(null=True) 
    previsto_dez = models.IntegerField(null=True) 

class VendedorModelo(models.Model):
    vendedor = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    modelo = models.ForeignKey(MotoPerfil, on_delete=models.CASCADE)
    aplicado = models.IntegerField(null=True) 
    previsto = models.IntegerField(null=True) 
    ano = models.IntegerField(null=True) 
    aplicado_jan = models.IntegerField(null=True) 
    aplicado_fev = models.IntegerField(null=True) 
    aplicado_mar = models.IntegerField(null=True) 
    aplicado_abr = models.IntegerField(null=True) 
    aplicado_mai = models.IntegerField(null=True) 
    aplicado_jun = models.IntegerField(null=True) 
    aplicado_jul = models.IntegerField(null=True) 
    aplicado_ago = models.IntegerField(null=True) 
    aplicado_sete = models.IntegerField(null=True) 
    aplicado_out = models.IntegerField(null=True) 
    aplicado_nov = models.IntegerField(null=True) 
    aplicado_dez = models.IntegerField(null=True) 
    previsto_jan = models.IntegerField(null=True) 
    previsto_fev = models.IntegerField(null=True) 
    previsto_mar = models.IntegerField(null=True) 
    previsto_abr = models.IntegerField(null=True) 
    previsto_mai = models.IntegerField(null=True) 
    previsto_jun = models.IntegerField(null=True) 
    previsto_jul = models.IntegerField(null=True) 
    previsto_ago = models.IntegerField(null=True) 
    previsto_sete = models.IntegerField(null=True) 
    previsto_out = models.IntegerField(null=True) 
    previsto_nov = models.IntegerField(null=True) 
    previsto_dez = models.IntegerField(null=True)  

class CidadeModeloCota(models.Model):
    cidade = models.ForeignKey(Cidade, on_delete=models.CASCADE)
    modelo = models.ForeignKey(MotoPerfil, on_delete=models.CASCADE)
    aplicado = models.IntegerField(null=True) 
    previsto = models.IntegerField(null=True) 
    ano = models.IntegerField(null=True) 
    aplicado_jan = models.IntegerField(null=True) 
    aplicado_fev = models.IntegerField(null=True) 
    aplicado_mar = models.IntegerField(null=True) 
    aplicado_abr = models.IntegerField(null=True) 
    aplicado_mai = models.IntegerField(null=True) 
    aplicado_jun = models.IntegerField(null=True) 
    aplicado_jul = models.IntegerField(null=True) 
    aplicado_ago = models.IntegerField(null=True) 
    aplicado_sete = models.IntegerField(null=True) 
    aplicado_out = models.IntegerField(null=True) 
    aplicado_nov = models.IntegerField(null=True) 
    aplicado_dez = models.IntegerField(null=True) 
    previsto_jan = models.IntegerField(null=True) 
    previsto_fev = models.IntegerField(null=True) 
    previsto_mar = models.IntegerField(null=True) 
    previsto_abr = models.IntegerField(null=True) 
    previsto_mai = models.IntegerField(null=True) 
    previsto_jun = models.IntegerField(null=True) 
    previsto_jul = models.IntegerField(null=True) 
    previsto_ago = models.IntegerField(null=True) 
    previsto_sete = models.IntegerField(null=True) 
    previsto_out = models.IntegerField(null=True) 
    previsto_nov = models.IntegerField(null=True) 
    previsto_dez = models.IntegerField(null=True) 

class VendedorModeloCota(models.Model):
    vendedor = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    modelo = models.ForeignKey(MotoPerfil, on_delete=models.CASCADE)
    aplicado = models.IntegerField(null=True) 
    previsto = models.IntegerField(null=True) 
    ano = models.IntegerField(null=True) 
    aplicado_jan = models.IntegerField(null=True) 
    aplicado_fev = models.IntegerField(null=True) 
    aplicado_mar = models.IntegerField(null=True) 
    aplicado_abr = models.IntegerField(null=True) 
    aplicado_mai = models.IntegerField(null=True) 
    aplicado_jun = models.IntegerField(null=True) 
    aplicado_jul = models.IntegerField(null=True) 
    aplicado_ago = models.IntegerField(null=True) 
    aplicado_sete = models.IntegerField(null=True) 
    aplicado_out = models.IntegerField(null=True) 
    aplicado_nov = models.IntegerField(null=True) 
    aplicado_dez = models.IntegerField(null=True) 
    previsto_jan = models.IntegerField(null=True) 
    previsto_fev = models.IntegerField(null=True) 
    previsto_mar = models.IntegerField(null=True) 
    previsto_abr = models.IntegerField(null=True) 
    previsto_mai = models.IntegerField(null=True) 
    previsto_jun = models.IntegerField(null=True) 
    previsto_jul = models.IntegerField(null=True) 
    previsto_ago = models.IntegerField(null=True) 
    previsto_sete = models.IntegerField(null=True) 
    previsto_out = models.IntegerField(null=True) 
    previsto_nov = models.IntegerField(null=True) 
    previsto_dez = models.IntegerField(null=True)  
