# Generated by Django 2.2.7 on 2020-04-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.CharField(max_length=30)),
                ('Data', models.DateField()),
                ('Nota_Fiscal', models.IntegerField()),
                ('Serie', models.IntegerField()),
                ('Valor_da_Nota', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Veiculo', models.CharField(max_length=100)),
                ('Chassi', models.CharField(max_length=100)),
                ('Forma_Pagamento', models.CharField(max_length=100)),
                ('Vendedor', models.CharField(max_length=100)),
                ('Cliente', models.CharField(max_length=100)),
                ('CPF_CNPJ_Cliente', models.IntegerField()),
                ('Novo', models.BooleanField()),
                ('Quantidade', models.IntegerField()),
                ('Operacao_Interna', models.CharField(max_length=100)),
                ('Data_Compra', models.DateField()),
                ('Custo_Medio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Margem', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Margem_Porcentagem', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Ano_Fab', models.IntegerField()),
                ('Ano_Modelo', models.IntegerField()),
                ('Municipio', models.CharField(max_length=100)),
                ('Valor_Tabela', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Emp_Funcionario', models.CharField(max_length=100)),
                ('Motivo_Devolucao', models.CharField(max_length=250)),
                ('Cor', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=100)),
                ('Telefone', models.CharField(max_length=50)),
                ('Celular', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('Placa', models.IntegerField()),
                ('Despesa_Oficina', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Despesa_Financeira', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Valor_Venda_Gerencial', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Preco_PPS', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Base_Comissao', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Forma_Fabrica', models.CharField(max_length=50)),
                ('Sub_Forma_Fabrica', models.CharField(max_length=50)),
                ('Modalidade_Venda', models.CharField(max_length=100)),
                ('Grupo_Pessoa_Vendedor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanejadoRealizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planejado', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Planjeado')),
                ('realizado', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Realizado')),
                ('planejado_moto', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Planjeado Moto')),
                ('realizado_moto', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Realizado Moto')),
                ('planejado_cota', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Planjeado cota')),
                ('realizado_cota', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Realizado cota')),
                ('planejado_visita', models.IntegerField(verbose_name='Realizado visita')),
                ('realizado_visita', models.IntegerField(default=0, verbose_name='Realizado visita')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('regiao', models.CharField(max_length=50, verbose_name='Regiao')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('ano', models.IntegerField(verbose_name='Ano')),
            ],
        ),
    ]
