# Generated by Django 2.2.7 on 2020-04-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='Placa',
            field=models.CharField(max_length=50),
        ),
    ]
