# Generated by Django 2.2.7 on 2020-04-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200407_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='Base_Comissao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='moto',
            name='Despesa_Financeira',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='moto',
            name='Despesa_Oficina',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='moto',
            name='Preço_PPS',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='moto',
            name='Valor_Venda_Gerencial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
