# Generated by Django 2.2.7 on 2020-04-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200408_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cota',
            name='Data_da_Contemplacao',
            field=models.DateField(null=True),
        ),
    ]
