# Generated by Django 2.2.7 on 2020-04-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200408_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cota',
            name='Data_da_Contemplacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
