# Generated by Django 2.2.7 on 2020-04-10 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200408_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planejadorealizado',
            name='realizado',
        ),
        migrations.RemoveField(
            model_name='planejadorealizado',
            name='realizado_cota',
        ),
        migrations.RemoveField(
            model_name='planejadorealizado',
            name='realizado_moto',
        ),
        migrations.RemoveField(
            model_name='planejadorealizado',
            name='realizado_visita',
        ),
    ]
