# Generated by Django 2.2.7 on 2020-04-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200410_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejadorealizado',
            name='planejado_moto',
            field=models.IntegerField(verbose_name='Planjeado Moto'),
        ),
    ]
