# Generated by Django 2.2.7 on 2020-04-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200412_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotoPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('avatar', models.CharField(max_length=100, verbose_name='avatar')),
            ],
        ),
    ]
