# Generated by Django 2.2.7 on 2020-04-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_motoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoperfil',
            name='avatar',
            field=models.CharField(max_length=400, verbose_name='avatar'),
        ),
    ]
