# Generated by Django 2.2.7 on 2020-04-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200415_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cota',
            name='Porcentagem_Amortizado',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
