# Generated by Django 2.2.7 on 2020-05-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200416_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalMesalMoto2019',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('qtd', models.IntegerField(verbose_name='Quantidade')),
            ],
        ),
        migrations.AlterField(
            model_name='moto',
            name='Novo',
            field=models.BooleanField(default=True),
        ),
    ]
