# Generated by Django 2.2.7 on 2020-05-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200505_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalmensalmoto2019',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
    ]
