# Generated by Django 2.2.7 on 2020-05-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200505_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='Vendedor_cpf',
            field=models.CharField(default='0315654654', max_length=100),
            preserve_default=False,
        ),
    ]
