# Generated by Django 2.2.7 on 2020-05-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_moto_vendedor_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='Cancelada',
            field=models.BooleanField(null=True, verbose_name='Cancelada'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='regiao',
            field=models.CharField(choices=[('JNB', 'JNB'), ('SFC', 'SFC'), ('JNR', 'JNR'), ('OUTROS', 'OUTROS')], max_length=100, verbose_name='Regiao'),
        ),
    ]
