# Generated by Django 2.2.7 on 2020-06-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_planejadomoto_sazonalidadecidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='SazonalidadeVendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor_nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('vendedor_cpf', models.CharField(max_length=100, verbose_name='CPF')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('percentual', models.FloatField(verbose_name='Porcentual')),
                ('vl_total_anual', models.IntegerField(verbose_name='Valor total no ano')),
                ('ano_base', models.IntegerField(verbose_name='Ano Base')),
            ],
        ),
    ]
