# Generated by Django 2.2.7 on 2020-06-04 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_sazonalidaderegiao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SazonalidadeModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('percentual', models.FloatField(verbose_name='Porcentual')),
                ('vl_total_anual', models.IntegerField(verbose_name='Valor total no ano')),
                ('ano_base', models.IntegerField(verbose_name='Ano Base')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MotoPerfil')),
            ],
        ),
    ]
