# Generated by Django 2.2.7 on 2020-06-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_sazonalidademodelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sazonalidademodelo',
            name='regiao',
            field=models.CharField(choices=[('JNB', 'JNB'), ('SFC', 'SFC'), ('JNR', 'JNR'), ('OUTROS', 'OUTROS')], default=1, max_length=100, verbose_name='Região'),
            preserve_default=False,
        ),
    ]
