# Generated by Django 2.2.7 on 2020-07-07 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0029_sazonalidademodelo_regiao'),
        ('account', '0007_auto_20200515_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendedorModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicado', models.IntegerField(null=True)),
                ('previsto', models.IntegerField(null=True)),
                ('ano', models.IntegerField(null=True)),
                ('jan', models.IntegerField(null=True)),
                ('fev', models.IntegerField(null=True)),
                ('mar', models.IntegerField(null=True)),
                ('abr', models.IntegerField(null=True)),
                ('mai', models.IntegerField(null=True)),
                ('jun', models.IntegerField(null=True)),
                ('jul', models.IntegerField(null=True)),
                ('ago', models.IntegerField(null=True)),
                ('sete', models.IntegerField(null=True)),
                ('out', models.IntegerField(null=True)),
                ('nov', models.IntegerField(null=True)),
                ('dez', models.IntegerField(null=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='CidadeModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicado', models.IntegerField(null=True)),
                ('previsto', models.IntegerField(null=True)),
                ('ano', models.IntegerField(null=True)),
                ('jan', models.IntegerField(null=True)),
                ('fev', models.IntegerField(null=True)),
                ('mar', models.IntegerField(null=True)),
                ('abr', models.IntegerField(null=True)),
                ('mai', models.IntegerField(null=True)),
                ('jun', models.IntegerField(null=True)),
                ('jul', models.IntegerField(null=True)),
                ('ago', models.IntegerField(null=True)),
                ('sete', models.IntegerField(null=True)),
                ('out', models.IntegerField(null=True)),
                ('nov', models.IntegerField(null=True)),
                ('dez', models.IntegerField(null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cidade')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MotoPerfil')),
            ],
        ),
    ]
