# Generated by Django 2.2.7 on 2020-07-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_sazonalidademodelo_regiao'),
        ('metas', '0002_auto_20200707_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedormodelo',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.MotoPerfil'),
            preserve_default=False,
        ),
    ]
