# Generated by Django 2.2.7 on 2020-07-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0003_vendedormodelo_modelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidademodelo',
            old_name='aplicado_ano',
            new_name='ano',
        ),
        migrations.RemoveField(
            model_name='vendedormodelo',
            name='aplicado_ano',
        ),
    ]
