# Generated by Django 2.2.7 on 2020-07-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200515_1550'),
        ('core', '0030_sazonalidadecidadecota_sazonalidademodelocota_sazonalidaderegiaocota_sazonalidadevendedorcota'),
        ('metas', '0004_auto_20200707_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendedorModeloCota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicado', models.IntegerField(null=True)),
                ('previsto', models.IntegerField(null=True)),
                ('ano', models.IntegerField(null=True)),
                ('aplicado_jan', models.IntegerField(null=True)),
                ('aplicado_fev', models.IntegerField(null=True)),
                ('aplicado_mar', models.IntegerField(null=True)),
                ('aplicado_abr', models.IntegerField(null=True)),
                ('aplicado_mai', models.IntegerField(null=True)),
                ('aplicado_jun', models.IntegerField(null=True)),
                ('aplicado_jul', models.IntegerField(null=True)),
                ('aplicado_ago', models.IntegerField(null=True)),
                ('aplicado_sete', models.IntegerField(null=True)),
                ('aplicado_out', models.IntegerField(null=True)),
                ('aplicado_nov', models.IntegerField(null=True)),
                ('aplicado_dez', models.IntegerField(null=True)),
                ('previsto_jan', models.IntegerField(null=True)),
                ('previsto_fev', models.IntegerField(null=True)),
                ('previsto_mar', models.IntegerField(null=True)),
                ('previsto_abr', models.IntegerField(null=True)),
                ('previsto_mai', models.IntegerField(null=True)),
                ('previsto_jun', models.IntegerField(null=True)),
                ('previsto_jul', models.IntegerField(null=True)),
                ('previsto_ago', models.IntegerField(null=True)),
                ('previsto_sete', models.IntegerField(null=True)),
                ('previsto_out', models.IntegerField(null=True)),
                ('previsto_nov', models.IntegerField(null=True)),
                ('previsto_dez', models.IntegerField(null=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MotoPerfil')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='CidadeModeloCota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicado', models.IntegerField(null=True)),
                ('previsto', models.IntegerField(null=True)),
                ('ano', models.IntegerField(null=True)),
                ('aplicado_jan', models.IntegerField(null=True)),
                ('aplicado_fev', models.IntegerField(null=True)),
                ('aplicado_mar', models.IntegerField(null=True)),
                ('aplicado_abr', models.IntegerField(null=True)),
                ('aplicado_mai', models.IntegerField(null=True)),
                ('aplicado_jun', models.IntegerField(null=True)),
                ('aplicado_jul', models.IntegerField(null=True)),
                ('aplicado_ago', models.IntegerField(null=True)),
                ('aplicado_sete', models.IntegerField(null=True)),
                ('aplicado_out', models.IntegerField(null=True)),
                ('aplicado_nov', models.IntegerField(null=True)),
                ('aplicado_dez', models.IntegerField(null=True)),
                ('previsto_jan', models.IntegerField(null=True)),
                ('previsto_fev', models.IntegerField(null=True)),
                ('previsto_mar', models.IntegerField(null=True)),
                ('previsto_abr', models.IntegerField(null=True)),
                ('previsto_mai', models.IntegerField(null=True)),
                ('previsto_jun', models.IntegerField(null=True)),
                ('previsto_jul', models.IntegerField(null=True)),
                ('previsto_ago', models.IntegerField(null=True)),
                ('previsto_sete', models.IntegerField(null=True)),
                ('previsto_out', models.IntegerField(null=True)),
                ('previsto_nov', models.IntegerField(null=True)),
                ('previsto_dez', models.IntegerField(null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cidade')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MotoPerfil')),
            ],
        ),
    ]
