# Generated by Django 2.2.7 on 2020-04-07 18:08

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('VENDEDOR', 'VENDEDOR'), ('GERENTE', 'GERENTE'), ('SUPERVISOR', 'SUPERVISOR')], max_length=100)),
                ('regiao', models.CharField(choices=[('VENDEDOR', 'VENDEDOR'), ('GERENTE', 'GERENTE'), ('SUPERVISOR', 'SUPERVISOR')], max_length=100)),
                ('avatar', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='avatar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
