# Generated by Django 2.2.7 on 2020-04-10 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='regiao',
            field=models.CharField(choices=[('JNB', 'JNB'), ('SFC', 'SFC'), ('JNR', 'JNR')], max_length=100),
        ),
        migrations.CreateModel(
            name='PlanejadoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planejado', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Planjeado')),
                ('planejado_moto', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Planjeado Moto')),
                ('planejado_cota', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Planjeado cota')),
                ('planejado_visita', models.IntegerField(verbose_name='Realizado visita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
