# Generated by Django 2.2.7 on 2020-05-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200414_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
