# Generated by Django 2.2.7 on 2020-05-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_perfil_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(choices=[('VENDEDOR', 'VENDEDOR'), ('GERENTE', 'GERENTE'), ('SUPERVISOR', 'SUPERVISOR'), ('ADMIN', 'ADMIN')], max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='regiao',
            field=models.CharField(choices=[('JNB', 'JNB'), ('SFC', 'SFC'), ('JNR', 'JNR'), ('OUTROS', 'OUTROS')], max_length=100),
        ),
    ]
