# Generated by Django 2.2.7 on 2020-06-23 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0029_sazonalidademodelo_regiao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SazonalidadeModeloCidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(choices=[('JNB', 'JNB'), ('SFC', 'SFC'), ('JNR', 'JNR'), ('OUTROS', 'OUTROS')], max_length=100, verbose_name='Região')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('percentual', models.FloatField(verbose_name='Porcentual')),
                ('vl_total_anual', models.IntegerField(verbose_name='Valor total no ano')),
                ('ano_base', models.IntegerField(verbose_name='Ano Base')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cidade')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MotoPerfil')),
            ],
        ),
    ]
