# Generated by Django 2.2.7 on 2020-06-24 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_sazonalidademodelo_regiao'),
        ('planejado', '0002_sazonalidademodelovendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstEtapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(choices=[('JNB', 'JNB'), ('SFC', 'SFC'), ('JNR', 'JNR'), ('OUTROS', 'OUTROS')], max_length=100, verbose_name='Região')),
                ('ano', models.IntegerField(null=True)),
                ('jan', models.IntegerField(null=True)),
                ('fev', models.IntegerField(null=True)),
                ('mar', models.IntegerField(null=True)),
                ('abr', models.IntegerField(null=True)),
                ('mai', models.IntegerField(null=True)),
                ('jun', models.IntegerField(null=True)),
                ('jul', models.IntegerField(null=True)),
                ('ago', models.IntegerField(null=True)),
                ('sete', models.IntegerField(null=True)),
                ('out', models.IntegerField(null=True)),
                ('nov', models.IntegerField(null=True)),
                ('dez', models.IntegerField(null=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MotoPerfil')),
            ],
        ),
    ]
