# Generated by Django 2.2.7 on 2020-06-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejado', '0003_firstetapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstetapa',
            name='aplicado',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='firstetapa',
            name='previsto',
            field=models.IntegerField(null=True),
        ),
    ]
