# Generated by Django 2.2.7 on 2020-07-03 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_sazonalidademodelo_regiao'),
        ('planejado', '0004_auto_20200624_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotencialCidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anual', models.IntegerField(verbose_name='Anual')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cidade')),
            ],
        ),
    ]
