# Generated by Django 2.2.7 on 2020-07-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planejado', '0005_potencialcidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='potencialcidade',
            options={'verbose_name': 'PotencialCidade', 'verbose_name_plural': 'PotencialCidades'},
        ),
    ]
