# Generated by Django 2.2.7 on 2020-07-26 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_sazonalidadecidadecota_sazonalidademodelocota_sazonalidaderegiaocota_sazonalidadevendedorcota'),
        ('planejado', '0006_auto_20200707_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='SazonalidadeModeloVendedorCota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor_nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('vendedor_cpf', models.CharField(max_length=100, verbose_name='CPF')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('percentual', models.FloatField(verbose_name='Porcentual')),
                ('vl_total_anual', models.IntegerField(verbose_name='Valor total no ano')),
                ('ano_base', models.IntegerField(verbose_name='Ano Base')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MotoPerfil')),
            ],
        ),
        migrations.CreateModel(
            name='SazonalidadeModeloCidadeCota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(choices=[('JNB', 'JNB'), ('SFC', 'SFC'), ('JNR', 'JNR'), ('OUTROS', 'OUTROS')], max_length=100, verbose_name='Região')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('percentual', models.FloatField(verbose_name='Porcentual')),
                ('vl_total_anual', models.IntegerField(verbose_name='Valor total no ano')),
                ('ano_base', models.IntegerField(verbose_name='Ano Base')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cidade')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MotoPerfil')),
            ],
        ),
        migrations.CreateModel(
            name='PotencialCidadeCota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anual', models.IntegerField(verbose_name='Anual')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cidade')),
            ],
            options={
                'verbose_name': 'PotencialCidadeCota',
                'verbose_name_plural': 'PotencialCidadesCotas',
            },
        ),
        migrations.CreateModel(
            name='FirstEtapaCota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(choices=[('JNB', 'JNB'), ('SFC', 'SFC'), ('JNR', 'JNR'), ('OUTROS', 'OUTROS')], max_length=100, verbose_name='Região')),
                ('aplicado', models.IntegerField(null=True)),
                ('previsto', models.IntegerField(null=True)),
                ('ano', models.IntegerField(null=True)),
                ('jan', models.IntegerField(null=True)),
                ('fev', models.IntegerField(null=True)),
                ('mar', models.IntegerField(null=True)),
                ('abr', models.IntegerField(null=True)),
                ('mai', models.IntegerField(null=True)),
                ('jun', models.IntegerField(null=True)),
                ('jul', models.IntegerField(null=True)),
                ('ago', models.IntegerField(null=True)),
                ('sete', models.IntegerField(null=True)),
                ('out', models.IntegerField(null=True)),
                ('nov', models.IntegerField(null=True)),
                ('dez', models.IntegerField(null=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MotoPerfil')),
            ],
        ),
    ]
