# Generated by Django 2.2.7 on 2020-08-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planejado', '0007_firstetapacota_potencialcidadecota_sazonalidademodelocidadecota_sazonalidademodelovendedorcota'),
    ]

    operations = [
        migrations.AddField(
            model_name='potencialcidade',
            name='mensal',
            field=models.IntegerField(null=True, verbose_name='Mensal'),
        ),
        migrations.AlterField(
            model_name='potencialcidade',
            name='anual',
            field=models.IntegerField(null=True, verbose_name='Anual'),
        ),
    ]
